name: i_protect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: 3.23.4 #The version of Flutter used in this project.

dependencies:
  flutter:
    sdk: flutter


  # A
  auto_route: ^9.2.2  # A powerful routing library, supports features like nested routes and route guards.

  # C
  cupertino_icons: ^1.0.6  # A set of iOS-style icons for Flutter apps on iOS.
  curl_logger_dio_interceptor: ^1.0.0  # Logs Dio HTTP requests in a cURL-like format for easier debugging.

  # D
  dartz: ^0.10.1  # Provides functional data types like Either and Option in Dart.
  dio: ^5.0.1  # A powerful HTTP client library for Flutter, with support for interceptors, global configuration, and retry logic.

  # E
  easy_localization: ^3.0.0  # A localization library that makes it easy to handle internationalization in Flutter apps.

  # F
  flutter_bloc: ^8.0.1  # State management using the Bloc pattern for Flutter applications.
  flutter_screenutil: ^5.8.0  # Supports responsive design for multiple screen sizes.
  freezed_annotation: ^2.4.4  # Annotation support for the Freezed package to create immutable and sealed classes.

  # G
  gap: ^4.0.0  # Provides spacing between widgets in Flutter layouts.
  geocoding: ^2.1.0  # Converts addresses into geographical coordinates (geocode) and vice versa (reverse geocode).
  geolocator: ^11.0.0  # A GPS location library providing location data for Flutter apps.
  get_it: ^7.2.0  # Service locator for Flutter and Dart, helps with dependency injection.

  # I
  injectable: ^2.1.0  # Simplifies dependency registration with GetIt using code generation.
  intl: ^0.18.1  # Provides internationalization features like number formatting, date/time formatting, and translations.

  # J
  json_annotation: ^4.9.0  # Annotations to help with serializing/deserializing JSON in Dart.

  # L
  logger: ^1.1.0  # A lightweight logging library for Flutter and Dart, with support for multiple log outputs.

  # P
  pretty_dio_logger: ^1.4.0  # A Dio plugin for logging requests/responses in a more readable format.

  # R
  retrofit: ^4.0.1  # A library that simplifies making RESTful HTTP requests using code generation and annotations.

dev_dependencies:
  flutter_test:
    sdk: flutter

  # B
  build_runner: ^2.4.12  # A build system for Dart projects, allowing you to run code generation and other build tasks.

  # F
  freezed: ^2.5.7  # A package that simplifies the creation of immutable classes and unions/sealed classes in Dart.

  # I
  injectable_generator: ^2.6.2   # A code generator for injectable that simplifies dependency injection in Dart applications.

  # J
  json_serializable: ^6.8.0  # A code generator that simplifies JSON serialization/deserialization in Dart.

  # R
  auto_route_generator: ^9.0.0  # A code generator for the auto_route package to simplify route management.
  retrofit_generator: ^9.1.2  # A code generator for Retrofit, facilitating the creation of RESTful API clients.

  # L
  flutter_lints: ^3.0.0  # A set of recommended lints for Flutter projects to improve code quality and maintainability.

flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - assets/translations/
    - assets/translations/en-US.json
